// Comprehensive fix for all TypeScript errors
import React from 'react';
import { Metadata } from 'next';
import Script from 'next/script';
import './globals.css';

// Explicitly declare types for JSX elements
declare global {
  namespace JSX {
    interface IntrinsicElements {
      html: any;
      head: any;
      body: any;
    }
  }
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <Script
          async
          src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-8374802692176093"
          crossOrigin="anonymous"
        />
      </head>
      <body className="font-geist antialiased">
        {children}
      </body>
    </html>
  );
}
